import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ryan Bakker | Studio",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/ryan-lightmode-favicon.svg",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/ryan-darkmode-favicon.svg",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
